baseURL: "http://localhost:1313/"
languageCode: "en-gb"
defaultContentLanguage: "en-gb"
title: "Field Notes"
timeZone: "Europe/London"

languages:
  en-gb:
    languageName: "English (UK)"
    weight: 1

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

pagination:
  pagerSize: 10

outputs:
  home: ["HTML", "RSS", "JSON"]

permalinks:
  posts: "/posts/:year/:month/:slug/"
  weeknotes: "/weeknotes/:year/:slug/"

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

params:
  env: "development"
  description: "Field Notes"
  defaultTheme: "auto"
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: true
  comments: false
  socialIcons:
    - name: github
      url: https://github.com/you
  homeInfoParams:
    Title: "Hello."
    Content: "This site uses PaperMod. still finding my footing around here"

menu:
  main:
    - name: "Weeknotes"
      url: "/weeknotes/"
      weight: 10
    - name: "Posts"
      url: "/posts/"
      weight: 20
    - name: "RSS"
      url: "/index.xml"
      weight: 30
